### ISSUE TITLE
IIIF Integration

### ISSUE THREAD

**Issue by falafeljan** [pelagios/recogito-text-js#16]
Is an integration with IIIF of interest for RecogitoJS?

I can imagine some viewers like UV and Mirador, depending on their own progress with annotation editing, being interested in using RecogitoJS for creating/editing annotations. And if not, there might exist APIs for integrating RecogitoJS independently.

**Comment by rsimon** [comment]
Of intereset: absolutely! I had been thinking about Mirador 3 (since it's also built with React). But haven't looked into it for real yet. I guess it could/would be another module (in this repo, or a separate one), providing an alternative "outer shell" for the editor popup. That outer shell would handle the integration into Mirador, and then be compatible with the various "inner" components that slot into the editor popup.

Unfortunately, the editor popup, at the moment, is in a super-preliminary state. I still need to find a good architecture for the separation between popup container and the elements that slot into the container. (I imagine there will be control elements that are always there when the editor opens - like the row of PLACE-PERSON-EVENT buttons in original Recogito, the reply field etc. and "body elements" that each correspond to a body in the current annotation - a text comment, a place URI a.s.o. Some elements are also a mix of that - like the tag section. Anyways... still a bit of design work needed - and any input/feedback/suggestions welcome of course!)

**Comment by rsimon** [comment]
Now in progress in https://github.com/recogito/annotorious-openseadragon
