### ISSUE TITLE
Updating annotations

### ISSUE THREAD

**Issue by falafeljan** [pelagios/recogito-text-js#17]
Web annotations are identified [by their `id` attribute](https://www.w3.org/TR/annotation-model/#annotations). However, currently the `WebAnnotation` implementation here assumes equality of two annotations by JavaScript Object equality, which is true iff two variables point to the same object reference.
https://github.com/pelagios/recogito-text-js/blob/3a22c8083fa840eaebee1e80378656211e0671ca/recogito-text-highlights/src/annotation/WebAnnotation.js#L13-L15

In order to update annotations after creating them, I propose to simply check equality by ID. Also, highlighter spans would need to be recalculated if they have been updated.

I'd be glad to work on a PR for this!

**Comment by rsimon** [comment]
Hi @falafeljan,

sounds good. I see only one issue: when a fresh annotation is created in the UI, it doesn't have an ID at all. (That's because in the original Recogito, the server was in charge of handing out the IDs. Maybe this needs to be rethought overall, anyway.)

How about a combined approach? 

- We could test for JS equality first. If that returns true, we know we're talking about the same annotations (object equality, as you say).
- If object equality is false, check for the presence of ID attributes and compare those
- If there's no ID on `this` or `other`, return false

**Comment by rsimon** [comment]
Good point on recalculating the highlights. Indeed, the old Recogito never had to deal with annotations changing their position. But I agree RecogitoJS needs to support this. If you are happy to send a pull request - that would be fantastic!

**Comment by falafeljan** [comment]
I see the issue of the missing ID—ideally, a CRUD backend would handle it, which could simply be using the browser's LocalStorage and generate UUIDs. Anyway, using object equality as second means should work out fine!
